### PR TITLE
feat(#64): fill CacheTojo

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
1. `Tojos.KEY` -> `Tojos.ID_KEY` 
2. Add `toMap` method to `Tojo`
3. Init `CacheTojo` cache

Closes: #64

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you have a look, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you release a new version, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.1`

**Pull request merged**
