### PR TITLE
#16 Sync tojos

### PR DESCRIPTION
**Pull request by l3r8yJ**
This is not the final version, I would like to know if I am moving in the right direction or not?

### CODE REVIEW

**Comment by l3r8yJ** [comment]
@yegor256 take a look please)

**Comment by yegor256** [comment]
@l3r8yJ this implementation breaks a very important principle: https://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html You load the entire collection in the ctor. This is wrong. Why can't you just synchronize each method? Also, where are unit tests? See this: https://www.yegor256.com/2018/03/27/how-to-test-thread-safety.html

**Comment by l3r8yJ** [comment]
@yegor256 yes, I agree with what you said about unit tests, I didn't implement them because I thought my implementation was generally wrong) 
About the synchronization of the whole method. Idea highlights the inspection about not marking the whole method as `synchronized ` so I highlighted individual blocks.  
I will read the articles correct the implementation and send another pull request, thanks a lot for the review!

**Comment by l3r8yJ** [comment]
@yegor256 also, can you assign this issue to me?

**Pull request closed without merging**
